[package]
name = "rustwasm-hello-world"
version = "0.1.0"
authors = ["Brandon Lucia <blucia@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.0"
rand = { version = "0.7", features = ["wasm-bindgen"] }
